config/routes.rb
Rails.application.routes.draw do

  root 'epigene_welcome#index'
  get '/description/queries' => 'epigene_welcome#description_queries', as: :description_queries
  get 'epifactors/' => 'epigene_welcome#index', as: :epigene_index
  get 'epigenes/' => 'epigene_welcome#index'
  get 'description' => 'epigene_welcome#description', as: :epigene_description
  post 'epifactors/search' => 'epigene_welcome#search', as: :epigene_search
  post 'epigenes/search' => 'epigene_welcome#search'

  resources :genes, only: [:show, :index]
  resources :protein_complexes, only: [:show, :index]
  resources :histones, only: [:show, :index]
  resources :samples, only: [:show, :index], constraints: {:id => /CNhs\d+/}

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= page_title
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    - if content_for?(:meta_description)
      %meta{name: 'description', content: yield(:meta_description)}
    = csrf_meta_tags
    :plain
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-61972442-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-61972442-1');
      </script>

  %body
    %header
      = nav_bar do
        = menu_group do
          = menu_item 'Home', root_path
          = menu_item 'Genes', genes_path, data: {toggle: 'tooltip', placement: 'right', title: 'Please note that the whole table may take a few seconds to load.'}, class: 'has-tooltip'
          = menu_item 'Сomplexes', protein_complexes_path
          = menu_item 'Histones and Protamines', histones_path
          = menu_item 'Expression', samples_path, data: {toggle: 'tooltip', placement: 'right', title: 'Please note that the whole table may take a few seconds to load.'}, class: 'has-tooltip'
          = menu_item 'Docs and Downloads', epigene_description_path
        = form_tag epigene_search_path, class: 'pull-right navbar-search' do
          = label_tag do
            Search:
            = text_field_tag 'search', params[:search]
          = select_tag 'kind', options_for_select({'Genes' => :genes, 'Сomplexes' => :protein_complexes, 'Histones and protamines' => :histones},  [:genes, :protein_complexes, :histones].include?(params[:controller].to_sym) ? params[:controller].to_sym : :genes)
          = submit_tag 'Search'
    %div{class: ['container', "controller-#{params[:controller]}", "action-#{params[:action]}"] }
      = yield
    %footer
      .grant Supported by RFBR grants 14-04-00180 and 15-34-20423.